-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 03:16:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema provnet_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema provnet_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provnet_database` DEFAULT CHARACTER SET utf8 ;
USE `provnet_database` ;

-- -----------------------------------------------------
-- Table `provnet_database`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provnet_database`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL DEFAULT 1,
  `status` VARCHAR(10) NOT NULL DEFAULT 'active',
  `gender` VARCHAR(7) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provnet_database`.`bans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provnet_database`.`bans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `description` TINYTEXT NOT NULL,
  `type` VARCHAR(6) NOT NULL DEFAULT 'temp',
  `days` INT NULL DEFAULT 0,
  `done_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bans_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_bans_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `provnet_database`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provnet_database`.`contact_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provnet_database`.`contact_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(75) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `content` TINYTEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provnet_database`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provnet_database`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `url` VARCHAR(255) NOT NULL DEFAULT '#',
  `count` INT NOT NULL,
  `read_at` TIMESTAMP NULL,
  `clicked_in` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `notificationscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
